rails/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :api do
    devise_for :users, skip: :registrations
    devise_for :students, :teachers, controllers: { registrations: "api/registrations" }, skip: :sessions
  end

  scope '/api' do
    ## FRONTEND ROUTES
    root to: 'pages#home'
    get 'auth' => 'pages#auth'
    get '/assignments/:assignment_id/edit' => 'assignments#edit', as: 'edit_assignment'
    put '/assignments/:assignment_id/edit' => 'assignments#update', as: 'update_assignment'
    resources :courses
    get '/dashboard' => 'dashboard#index', as: 'student_dashboard'

    ## USER AUTHENTICATION
    devise_for :users, skip: :registrations
    devise_for :students, :teachers, controllers: { registrations: "registrations" }, skip: :sessions

    ## FRONTEND API
    post '/courses/:course_id/assignments' => 'assignments#create', as: 'assignments'
    delete '/courses/:course_id/assignments/:assignment_id' => 'assignments#destroy', as: 'assignment'
    post '/enrollments' => 'enrollments#create', as: 'enrollments'
    patch "/student_assignments/:id/complete" => "student_assignments#complete", as: :complete_student_assignment

    ## REALTIME QUIZ CENTER
    get '/quizcenter' => "quiz_center#index", as: :quiz_center
    get '/quizcenter/manage/:id' => "quiz_center#manage", as: :quiz_center_manage
    post '/quizcenter/manage/:id/start' => "quiz_center#change_start_status"
    get '/quizcenter/take/:id' => "quiz_center#take", as: :quiz_center_take
    post '/quizcenter/take/:id/response' => 'quiz_center#update', as: :quiz_center_response
    post '/pusher/auth' => "quiz_center#pusher_auth"
  end
end

rails/app/views/layouts/_courses.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Courses <span class="caret"></span></a>
  <ul class="dropdown-menu">
    <% current_user.courses.where("courses.name IS NOT NULL").each do |course| %>
      <li> <%= link_to course.name, course_path(course) %> </li>
    <% end %>

    <% if current_user.is_a?(Teacher) %>
      <li>
        <%= link_to new_course_path do %>
          <span class="glyphicon glyphicon-plus"></span> New Course
        <% end %>
      </li>
    <% else # Student %>
      <li>
        <button type="button" class="btn btn-primary btn-sm" id="new-enrollment-toggler" data-toggle="modal" data-target="#newEnrollment">
          <span class="glyphicon glyphicon-plus"></span> New Enrollment
        </button>
      </li>
    <% end %>
  </ul>
</li>

<!--  -->

rails/app/views/layouts/_enrollment.html.erb
<div class="modal fade" id="newEnrollment" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Enrollment</h4>
      </div>
      <div class="modal-body">

        <%= form_tag enrollments_path, id: "new-enrollment-form" do %>
          <div class="form-group">
          <%= label_tag "code", "Please enter the code of the course you want to enroll in." %>
          <%= text_field_tag "enrollment[code]", nil, placeholder: "abc123", class: "form-control new-enrollment-code" %>
          </div>
          <p>Not sure where to find this? Speak to the teacher whose class you want to enroll in.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= button_tag "Submit", type:"submit", class: "btn btn-primary new-enrollment-btn popup-submit" %>
      </div>
        <% end %>

    </div>
  </div>
</div>

rails/app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
        <span class="glyphicon glyphicon-globe"></span> Globe
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if user_signed_in? %>
          <%= render "layouts/courses" %>
          <li> <%= link_to "Quiz Center", quiz_center_path %> </li>
          <% if student_signed_in? %>
            <li> <%= link_to "Account Settings", edit_student_registration_path %> </li>
            <li> <%= link_to "Log out", destroy_user_session_path, method: :delete %> </li>
          <% elsif teacher_signed_in? %>
            <li> <%= link_to "Account Settings", edit_teacher_registration_path %> </li>
            <li> <%= link_to "Log out", destroy_user_session_path, method: :delete %> </li>
          <% end %>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Globe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//js.pusher.com/3.0/pusher.min.js"></script>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <%= render "layouts/header" %>

  <div class="container">
    <%= render "layouts/enrollment" %>
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-success alert-dismissible", role: "alert") %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>