rails/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :api do
    devise_for :users, skip: :registrations
    devise_for :students, :teachers, controllers: { registrations: "api/registrations" }, skip: :sessions
  end

  scope '/api' do
    ## FRONTEND ROUTES
    root to: 'pages#home'
    get 'auth' => 'pages#auth'
    get '/assignments/:assignment_id/edit' => 'assignments#edit', as: 'edit_assignment'
    put '/assignments/:assignment_id/edit' => 'assignments#update', as: 'update_assignment'
    resources :courses
    get '/dashboard' => 'dashboard#index', as: 'student_dashboard'

    ## USER AUTHENTICATION
    devise_for :users, skip: :registrations
    devise_for :students, :teachers, controllers: { registrations: "registrations" }, skip: :sessions

    ## FRONTEND API
    post '/courses/:course_id/assignments' => 'assignments#create', as: 'assignments'
    delete '/courses/:course_id/assignments/:assignment_id' => 'assignments#destroy', as: 'assignment'
    post '/enrollments' => 'enrollments#create', as: 'enrollments'
    patch "/student_assignments/:id/complete" => "student_assignments#complete", as: :complete_student_assignment

    ## REALTIME QUIZ CENTER
    get '/quizcenter' => "quiz_center#index", as: :quiz_center
    get '/quizcenter/manage/:id' => "quiz_center#manage", as: :quiz_center_manage
    post '/quizcenter/manage/:id/start' => "quiz_center#change_start_status"
    get '/quizcenter/take/:id' => "quiz_center#take", as: :quiz_center_take
    post '/quizcenter/take/:id/response' => 'quiz_center#update', as: :quiz_center_response
    post '/pusher/auth' => "quiz_center#pusher_auth"
  end
end

rails/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_teacher!, except: :show
  before_action :authenticate_user!
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :correct_teacher, only: [:edit, :update, :destroy]
  before_action :correct_user, only: :show

  # GET /courses
  # GET /courses.json
  def index
    @courses = current_teacher.courses.all
  end

  # GET /courses/1
  def show
    @assignments = @course.assignments.where("DATE(assignments.due_date) >= ?", Date.today).all
  end

  # GET /courses/new
  def new
    @course = current_teacher.courses.build
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  def create
    @course = current_teacher.courses.build(course_params)

    if @course.save
      redirect_to @course, notice: 'Course was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /courses/1
  def update
    if @course.update(course_params)
      redirect_to @course, notice: 'Course was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /courses/1
  def destroy
    if @course.destroy
      render json: {}, status: 200
    else
      render json: {}, status: 500
    end
  end

  private
    def correct_teacher
      @course = current_teacher.courses.find_by(id: params[:id])
      redirect_to root_path, 'You do not have permission to view/edit this course' if @course.nil?
    end

    def correct_user
      @course = current_user.courses.find_by(id: params[:id])
      redirect_to root_path, 'You do not have permission to view/edit this course' if @course.nil?
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:description, :name, :teacher_id)
    end
end

rails/app/helpers/courses_helper.rb
module CoursesHelper
end

rails/app/views/courses/_assignments.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Due Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assignments.each do |assignment| %>
      <tr>
        <td>
          <% if assignment.category == "Homework" %>
            <span class="label label-default">Homework</span>
          <% elsif assignment.category == "Interactive Assessment" %>
            <span class="label label-primary">IA</span>
          <% elsif assignment.category == "Quiz" %>
            <span class="label label-warning">Quiz</span>
          <% elsif assignment.category == "Test" %>
            <span class="label label-danger">Test</span>
          <% elsif assignment.category == "Project" %>
            <span class="label label-info">Project</span>
          <% end %>
          <%= assignment.name %>
        </td>
        <td><%= assignment.due_date.strftime("%A, %B %d") %></td>
        <% if current_teacher && current_teacher == @course.teacher %>
          <td>
            <%= link_to edit_assignment_path(assignment), class: "btn btn-default btn-sm" do %>
              <span class='glyphicon glyphicon-pencil'></span> Edit Assignment
            <% end %>
          </td>
          <td>
            <button class="btn btn-sm btn-default" data-assignment-id="<%= assignment.id %>" id="delete-assignment">
              Delete
            </button>
          </td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

rails/app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

rails/app/views/courses/_new_assignment.html.erb
<button type="button" class="btn btn-primary btn-lg" id="new-assignment-toggler" data-toggle="modal" data-target="#newAssignment">
  <span class="glyphicon glyphicon-plus"></span> New Assignment
</button>

<div class="modal fade" id="newAssignment" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Assignment</h4>
      </div>
      <div class="modal-body">

        <%= form_tag assignments_path(@course), id: "new-assignment-form" do %>
          <input type="hidden" name="assignment[course_id]" value="<%= @course.id %>" id="assignment_course_id" class="new-assignment-course_id">
          <div class="form-group">
           <%= label_tag "name" %>
            <%= text_field_tag "assignment[name]", nil, placeholder: "abc123", class: "form-control new-assignment-name" %>
          </div>
          <div class="form-group">
            <%= label_tag "description" %>
            <input class="form-control new-assignment-description" id="assignment[description]" value="" placeholder="" type="hidden" name="assignment[description]">
            <trix-editor class="trix-content" input="assignment[description]"></trix-editor>
          </div>
          <div class="form-group">
            <%= label_tag "due_date", "Due Date" %>
            <input type="text" data-provide='datepicker' name="assignment[due_date]" class="form-control new-assignment-duedate">
          </div>

          <div class="form-group">
            <label for="assignment_category">Category</label><br>
            <select name="assignment[category]" id="assignment_category" class="form-control new-assignment-category">
              <option selected="selected" value="Homework">Homework</option>
              <option selected="selected" value="Interactive Assessment">Interactive Assessment</option>
              <option selected="selected" value="Quiz">Quiz</option>
              <option selected="selected" value="Test">Test</option>
              <option selected="selected" value="Project">Project</option>
            </select>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= button_tag "Submit", type:"submit", class: "btn btn-primary new-assignment-btn popup-submit" %>
      </div>
        <% end %>

    </div>
  </div>
</div>

rails/app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

rails/app/views/courses/index.html.erb
<h1>My Courses</h1>

<hr>

<div class="row">
  <% @courses.each do |course| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <div class="caption">
          <h3> <%= course.name %> </h3>
          <p><b>Code:</b> <%= course.code %> </p>
          <p><b>Description:</b> <%= course.description %> </p>
          <% if course.students.any? %>
            <p><b>Students Enrolled:</b> <%= course.students.count %></p>
          <% end %>
          <p>
            <%= link_to 'Show', course , class: 'btn btn-primary', role: 'button' %>
            <%= link_to 'Edit', edit_course_path(course), class: 'btn btn-default', role: 'button' %>
            <button class="btn btn-default" data-course-id="<%= course.id %>" id="delete-course">
              Destroy
            </button>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>

<%= link_to 'New Course', new_course_path, class: 'btn btn-lg btn-primary' %>

rails/app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

rails/app/views/courses/show.html.erb
<div class="page-header center">
  <h1><%= @course.name %> <small> <%= @course.code %> </small></h1>
</div>

<div class="row">
  <div class="col-md-6">
    <p>
      <strong>Course Description:</strong>
      <%= @course.description %>
    </p>

    <hr>

    <p><b><%= @course.students.count %> Enrolled Students:</b></p>
    <% if @course.students.any? %>
      <ul>
        <% @course.students.each do |student| %>
          <li> <%= student.name %> </li>
        <% end %>
      </ul>
    <% else %>
      <p>No students currently enrolled in this course.</p>
    <% end %>

    <hr>

    <% if current_teacher && @course.teacher == current_teacher %>
      <%= link_to 'Edit', edit_course_path(@course) %> |
    <% end %>
    <%= link_to 'Back', courses_path %>
  </div>

  <div class="col-md-6">
    <p>Upcoming Assignments:</p>
    <%= render "courses/assignments" %>

    <% if current_teacher && @course.teacher == current_teacher %>
      <%= render 'courses/new_assignment' %>
    <% end %>
  </div>
</div>