config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  ## FRONTEND ROUTES
  root to: 'pages#home'
  get 'auth' => 'pages#auth'
  get '/assignments/:assignment_id/edit' => 'assignments#edit', as: 'edit_assignment'
  put '/assignments/:assignment_id/edit' => 'assignments#update', as: 'update_assignment'
  resources :courses
  get '/dashboard' => 'dashboard#index', as: 'student_dashboard'

  ## USER AUTHENTICATION
  devise_for :users, skip: :registrations
  devise_for :students, :teachers, controllers: { registrations: "registrations" }, skip: :sessions

  ## FRONTEND API
  post '/courses/:course_id/assignments' => 'assignments#create', as: 'assignments'
  delete '/courses/:course_id/assignments/:assignment_id' => 'assignments#destroy', as: 'assignment'
  post '/enrollments' => 'enrollments#create', as: 'enrollments'
  patch "/student_assignments/:id/complete" => "student_assignments#complete", as: :complete_student_assignment
  post '/courses/:course_id/course_notifications' => 'course_notifications#create', as: 'course_notifications'

  ## SIDEKIQ ADMIN
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  ## REALTIME QUIZ CENTER
  get '/quizcenter' => "quiz_center#index", as: :quiz_center
  get '/quizcenter/manage/:id' => "quiz_center#manage", as: :quiz_center_manage
  post '/quizcenter/manage/:id/start' => "quiz_center#change_start_status"
  get '/quizcenter/take/:id' => "quiz_center#take", as: :quiz_center_take
  post '/quizcenter/take/:id/response' => 'quiz_center#update', as: :quiz_center_response
  post '/pusher/auth' => "quiz_center#pusher_auth"
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :assignments, dependent: :destroy
  has_many :course_notifications, dependent: :destroy
  has_many :enrollments, dependent: :destroy
  has_many :students, through: :enrollments
  belongs_to :teacher
  ###
  before_save :generate_course_code
  validates_presence_of :name

  private

  def generate_course_code
    code = SecureRandom.hex(4)
    if Course.find_by(code: code) != nil
      generate_course_code
    else
      self.code ||= code
    end
  end
end

app/models/course_notification.rb
class CourseNotification < ActiveRecord::Base
  belongs_to :course

  validates_presence_of :body
  validates_presence_of :subject
end

app/models/invite_code.rb
class InviteCode < ActiveRecord::Base
  before_save :generate_course_code
  validates_uniqueness_of :code

  private

  def generate_course_code
    code = SecureRandom.hex(4)
    if InviteCode.find_by(code: code) != nil
      generate_course_code
    else
      self.code ||= code
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise_params, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def configure_devise_params
    [:sign_up, :account_update].each do |s|
      devise_parameter_sanitizer.for(s) do |u|
        u.permit(:invite_code, :name, :type, :email, :password, :password_confirmation, :current_password)
      end
    end
  end

  def redirect
    redirect_to root_path, notice: 'Unauthorized.'
  end

  %w(Student Teacher).each do |k|
    define_method "current_#{ k.underscore }" do
      current_user if current_user.is_a?(k.constantize)
    end

    define_method "authenticate_#{ k.underscore }!" do
      |opts={}| send("current_#{ k.underscore }") || redirect
    end

    define_method "#{ k.underscore }_signed_in?" do
      !send("current_#{ k.underscore }").nil?
    end
  end
end

app/controllers/course_notifications_controller.rb
class CourseNotificationsController < ApplicationController
  def create
    @course_notification = CourseNotification.new(course_notification_params)
    if @course_notification.save
      CourseNotificationWorker.perform_async(@course_notification.id)
      render json: {}, status: 200
    end
  end

  private

  def course_notification_params
    params.require(:course_notification).permit(:body, :course_id, :subject)
  end
end

app/controllers/invite_codes_controller.rb
class InviteCodesController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_site_admin
  before_action :set_invite_code, only: [:show, :edit, :update, :destroy]

  # GET /invite_codes
  def index
    @invite_codes = InviteCode.all
  end

  # GET /invite_codes/1
  def show
  end

  # GET /invite_codes/new
  def new
    @invite_code = InviteCode.new
  end

  # GET /invite_codes/1/edit
  def edit
  end

  # POST /invite_codes
  def create
    @invite_code = InviteCode.new(invite_code_params)

    if @invite_code.save
      redirect_to @invite_code, notice: 'Invite code was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /invite_codes/1
  def update
    if @invite_code.update(invite_code_params)
      redirect_to @invite_code, notice: 'Invite code was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /invite_codes/1
  def destroy
    @invite_code.destroy
    redirect_to invite_codes_url, notice: 'Invite code was successfully destroyed.'
  end

  private
    def authenticate_site_admin
      redirect_to root_path, notice: 'Unauthorized.' unless current_user.school_admin?
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_invite_code
      @invite_code = InviteCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invite_code_params
      params.require(:invite_code).permit(:code, :for_school_admins, :for_teachers)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    if resource_name == :teacher
      @invite_code = params['teacher']['invite_code']
      if @invite_code.nil? or !InviteCode.where(code: @invite_code).any?
        redirect_to root_path, notice: 'Unauthorized'
      else
        params['teacher'].delete('invite_code')
        super
      end
    else
      super
    end
  end

  def new
    if resource_name == :teacher
      @invite_code = params[:invite_code]
      if params[:invite_code].nil? or !InviteCode.where(code: @invite_code).any?
        redirect_to root_path, notice: 'Unauthorized'
      else
        super
      end
    else
      super
    end
  end

  def sign_up(resource_name, resource)
    sign_in(:user, resource)
  end
end

app/helpers/course_notifications_helper.rb
module CourseNotificationsHelper
end

app/helpers/invite_codes_helper.rb
module InviteCodesHelper
end

app/views/courses/_new_course_notification.html.erb
<button type="button" class="btn btn-primary btn-lg" id="new-course-notification-toggler" data-toggle="modal" data-target="#newCourseNotification">
  <span class="glyphicon glyphicon-plus"></span> New Course Notification
</button>

<div class="modal fade" id="newCourseNotification" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Course Notification</h4>
      </div>
      <div class="modal-body">

        <%= form_tag course_notifications_path(@course), id: "new-course-notification-form" do %>
          <input type="hidden" name="course_notification[course_id]" value="<%= @course.id %>" id="course_notification_course_id" class="new-course-notification-course_id">
          <div class="form-group">
           <%= label_tag "subject" %>
            <%= text_field_tag "course_notification[subject]", nil, placeholder: "abc123", class: "form-control new-course-notification-subject" %>
          </div>
          <div class="form-group">
            <%= label_tag "body" %> <br>
            <input class="form-control new-course-notification-body" id="course_notification[body]" value="" placeholder="" type="hidden" name="course_notification[body]">
            <trix-editor class="trix-content" input="course_notification[body]"></trix-editor>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= button_tag "Submit", type:"submit", class: "btn btn-primary new-course-notification-btn popup-submit" %>
      </div>
        <% end %>

    </div>
  </div>
</div>

app/views/courses/show.html.erb
<div class="page-header center">
  <h1><%= @course.name %> <small> <%= @course.code %> </small></h1>
</div>

<div class="row">
  <div class="col-md-6">
    <p>
      <strong>Course Description:</strong>
      <%= @course.description %>
    </p>

    <hr>

    <p><b><%= @course.students.count %> Enrolled Students:</b></p>
    <% if @course.students.any? %>
      <ul>
        <% @course.students.each do |student| %>
          <li> <%= student.name %> </li>
        <% end %>
      </ul>
    <% else %>
      <p>No students currently enrolled in this course.</p>
    <% end %>

    <hr>

    <% if current_teacher && @course.teacher == current_teacher %>
      <%= link_to 'Edit', edit_course_path(@course) %> |
    <% end %>
    <%= link_to 'Back', courses_path %>
  </div>

  <div class="col-md-6">
    <p>Upcoming Assignments:</p>
    <%= render "courses/assignments" %>

    <% if current_teacher && @course.teacher == current_teacher %>
      <%= render 'courses/new_assignment' %>
      <%= render 'courses/new_course_notification' %>
    <% end %>
  </div>
</div>

app/views/invite_codes/_form.html.erb
<%= form_for(@invite_code) do |f| %>
  <% if @invite_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invite_code.errors.count, "error") %> prohibited this invite_code from being saved:</h2>

      <ul>
      <% @invite_code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.check_box :for_school_admins %>
    <%= f.label :for_school_admins, "If checked, this code can be used to register as a school admin" %>
  </div>

  <div class="form-group">
    <%= f.check_box :for_teachers %>
    <%= f.label :for_teachers, "If checked, this code can be used to register as a teacher" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/invite_codes/edit.html.erb
<h1>Editing Invite Code</h1>

<%= render 'form' %>

<%= link_to 'Show', @invite_code %> |
<%= link_to 'Back', invite_codes_path %>

app/views/invite_codes/index.html.erb
<div class="center">
  <h1>Invite Code Dashboard</h1>
  <p>You can use this dashboard to create invite codes for teachers, or other school admins.</p>
  <p>The only purpose of a school admin is to create invite codes for teachers or other school admins.</p>
</div>

<h1>All Invite Codes</h1>

<table class="table">
  <thead>
    <tr>
      <th>Code</th>
      <th>For school admins?</th>
      <th>For teachers?</td>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invite_codes.each do |invite_code| %>
      <tr>
        <td><%= link_to invite_code.code, new_teacher_registration_path(invite_code: invite_code.code) %></td>
        <td><%= invite_code.for_school_admins %></td>
        <td><%= invite_code.for_teachers %></td>
        <td><%= link_to 'Edit', edit_invite_code_path(invite_code) %></td>
        <td><%= link_to 'Destroy', invite_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invite code', new_invite_code_path %>

app/views/invite_codes/new.html.erb
<h1>New Invite Code</h1>

<%= render 'form' %>

<%= link_to 'Back', invite_codes_path %>

app/views/invite_codes/show.html.erb
<p>
  <strong>Code:</strong>
  <%= @invite_code.code %>
</p>

<p>
  <strong>For school admins?:</strong>
  <%= @invite_code.for_school_admins %>
</p>

<p>
  <strong>For teachers?:</strong>
  <%= @invite_code.for_teachers %>
</p>

<%= link_to 'Edit', edit_invite_code_path(@invite_code) %> |
<%= link_to 'Back', invite_codes_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
        <span class="glyphicon glyphicon-globe"></span> Globe
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if user_signed_in? %>
          <%= render "layouts/courses" %>
          <li> <%= link_to "Quiz Center", quiz_center_path %> </li>

          <% if student_signed_in? %>
            <li> <%= link_to "Account Settings", edit_student_registration_path %> </li>
            <li> <%= link_to "Log out", destroy_user_session_path, method: :delete %> </li>
          <% elsif teacher_signed_in? %>
            <% if current_teacher.school_admin == true %>
              <li> <%= link_to "Invite Code Dashboard", invite_codes_path %> </li>
            <% end %>
            <li> <%= link_to "Account Settings", edit_teacher_registration_path %> </li>
            <li> <%= link_to "Log out", destroy_user_session_path, method: :delete %> </li>
          <% end %>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/quiz_center/_presence_teacher_notifier.html.erb
<script>
  window.onload = function(){
    // Initial setup
    presenceChannel.bind('pusher:subscription_succeeded', function(members) {
      update_count(presenceChannel.members.count);
      members.each(function(member) {
        add_member(member.id);
      });
    });

    // Update status for new member
    presenceChannel.bind('pusher:member_added', function(member) {
      add_member(member.id);
      update_count(presenceChannel.members.count);
    });

    // Update status for departing member
    presenceChannel.bind('pusher:member_removed', function(member) {
      remove_member(member.id);
      update_count(presenceChannel.members.count);
    });

    // Change a member's status from offline to online
    function add_member(id){
      i = $("i").filter("[data-student-id='" + id + "']");
      i.removeClass("offline");
      i.addClass("online");
    }

    // Change a member's status from online to offline
    function remove_member(id){
      i = $("i").filter("[data-student-id='" + id + "']");
      i.removeClass("online");
      i.addClass("offline");
    }

    // Change count at the top of the page
    function update_count(count){
      real_count = count - 1;
      $(".online-count").html("<span class='online-count'>" +  real_count + "</span>");
    }
  }
</script>