rails/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :api do
    devise_for :users, skip: :registrations
    devise_for :students, :teachers, controllers: { registrations: "api/registrations" }, skip: :sessions
  end

  scope '/api' do
    ## FRONTEND ROUTES
    root to: 'pages#home'
    get 'auth' => 'pages#auth'
    get '/assignments/:assignment_id/edit' => 'assignments#edit', as: 'edit_assignment'
    put '/assignments/:assignment_id/edit' => 'assignments#update', as: 'update_assignment'
    resources :courses
    get '/dashboard' => 'dashboard#index', as: 'student_dashboard'

    ## USER AUTHENTICATION
    devise_for :users, skip: :registrations
    devise_for :students, :teachers, controllers: { registrations: "registrations" }, skip: :sessions

    ## FRONTEND API
    post '/courses/:course_id/assignments' => 'assignments#create', as: 'assignments'
    delete '/courses/:course_id/assignments/:assignment_id' => 'assignments#destroy', as: 'assignment'
    post '/enrollments' => 'enrollments#create', as: 'enrollments'
    patch "/student_assignments/:id/complete" => "student_assignments#complete", as: :complete_student_assignment

    ## REALTIME QUIZ CENTER
    get '/quizcenter' => "quiz_center#index", as: :quiz_center
    get '/quizcenter/manage/:id' => "quiz_center#manage", as: :quiz_center_manage
    post '/quizcenter/manage/:id/start' => "quiz_center#change_start_status"
    get '/quizcenter/take/:id' => "quiz_center#take", as: :quiz_center_take
    post '/quizcenter/take/:id/response' => 'quiz_center#update', as: :quiz_center_response
    post '/pusher/auth' => "quiz_center#pusher_auth"
  end
end

rails/app/views/pages/auth.html.erb
<h1 class='center'>Globe Authentication</h1>

<div class='row'>
  <div class='col-md-6'>
    <div class="panel panel-default">
      <div class="panel-heading">Registration</div>
      <div class="panel-body">
        <p> <%= link_to "Register as a student", new_student_registration_path %> </p>
        <p> <%= link_to "Register as a teacher", new_teacher_registration_path %> </p>
      </div>
    </div>
  </div>

  <div class='col-md-6'>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Login</h3>
      </div>
      <div class="panel-body">
        <p> <%= link_to "Login", new_user_session_path %> </p>
      </div>
    </div>
  </div>
</div>

rails/app/views/pages/home.html.erb
<h1 class='center'>Welcome to Globe!</h1>
<h3 class='center'>An awesome LMS.</h3>

<hr>

<% if teacher_signed_in? %>
  <h1 class='center'> <%= link_to 'My Courses', courses_path %> </h1>
  <h1 class='center'> <%= link_to 'Quiz Center', quiz_center_path %> </h1>
<% elsif student_signed_in? %>
    <h1 class='center'> <%= link_to 'Assignment Dashboard', student_dashboard_path %> </h1>
    <h1 class='center'> <%= link_to 'Quiz Center', quiz_center_path %> </h1>
<% else %>
  <h1 class='center'> <%= link_to 'Register or Sign In', auth_path %> </h1>
<% end %>